### ISSUE TITLE
Font Increase and Decrease error

### ISSUE THREAD

**Issue by wbuk** [brickfield/moodle-block_accessibility#126]
Hi

I have just installed the latest version and there is an error.
When you click A- or A+ you get an error message.
If says:

Error changing size: undefined undefined

Then the circular spinner just spins.

Also, the block has spaces for 3 different overlays, is there any chance you can increase this, as we work with a lot of schools and to be honest we need about 6 different overlays to cover all schools. 

If you need a screenshot of the error messages, please let me know.

Thank you.

**Comment by mchurchward** [comment]
Thanks for the report. Any extra info you can give will be appreciated.

**Comment by wbuk** [comment]
![block-error](https://user-images.githubusercontent.com/20259361/126227266-454b19bc-4a30-4062-ad22-d2410a9099bb.png)
 Here is a screenshot.  We have used this block for years and this is the first issue.  Students were using it today, the issue was caused by the update I did tonight.  I hope that helps.

**Comment by wbuk** [comment]
This was done in Opera, we have tried it on another PC and it seems to work.  Both use Opera and the same version of windows.  It is a little odd.  Might be clashing with something.

Also, the ATbar, does not work in an IFrame so we have disabled it now.  If there is any chance you can make it work in an IFrame, this would be very useful as our students need it.  We have tested it on 3 PC's, 2 Laptops and finally found it is an issue with it working in an IFrame.  It works fine with no IFrame on all our testbeds.  Please could you have a look at the code, it would be so much appreciated.   Thank you so much.

**Comment by mchurchward** [comment]
Hi. We have not been able to reliably replicate this issue. If you can determine steps / setups that can reliably replicate the issue, please provide them. For now, I am closing this issue as non-replicateable. If you do manage to get the steps, feel free to reopen or create a new issue.
