### ISSUE TITLE
User sent to CSS URL on login instead of site home

### ISSUE THREAD

**Issue by tim1mw** [brickfield/moodle-block_accessibility#127]
I've just upgraded to the new 1.39.01 (Build - 2021071301) (2021052400) release and have discovered a show-stopper bug which forced me to revert back to the earlier version. If the block is included on the site home page and the user is taken to that page after login, something triggers a redirect which causes the user to be sent to https://mysite.org/blocks/accessibility/userstyles.php?instance_id=7438 with the CSS code being shown to the user instead of the site home page.

Manually truncating the URL in the browser allows access to the home page, so this seems to be a faulty interaction with the login process. Reverting the plugin back to the previous release fixes the problem, so this bug seems to have been introduced with the 2021052400 release. I'm using Moodle 3.9.8.

![redirect-error](https://user-images.githubusercontent.com/11174402/126457026-f68cba14-3011-4c86-92ef-79f3e259f616.jpg)

**Comment by prosserg** [comment]
We have this same issue with the version code 2021052400 and moodle version 3.9.1

Disabling this block is the only means we have found to avoid causing our users seeing the css code (per above) after login.

**Comment by mchurchward** [comment]
This issue has been fixed and released as 1.39.02 in the plugins DB.
