### ISSUE TITLE
Block reports "Links opening into a new window should warn users in advance."

### ISSUE THREAD

**Issue by dgarciatotem** [brickfield/moodle-block_accessibility#152]
Hello, 

we've just started using Brickfield Accesibility Toolkit on our moodle 4.0.X installation. We've noticed that a lot of the issues it founds are related to "Links opening into a new window should warn users in advance." The problem is that we don't fully understand how to fix those issues. I've tried to add text in the link such us "opens in a new window" but that doesn't seem to make any effect.

You can see a couple of examples we've tried. One with the text visible and the other with the text hidden so users don't see that:

<img width="924" alt="image" src="https://github.com/brickfield/moodle-block_accessibility/assets/112547486/15ff4d50-dd12-4f5a-806d-6e5486a2a8a6">

Can you please give us some insight on this?

Thanks a lot in advance.
Kind regards

**Comment by dgarciatotem** [comment]
Hello, has anyone find out why this is happening or have a possible fix for this?

Thanks a lot in advance :)

**Comment by dgarciatotem** [comment]
Sorry I closed the issue by accident.

Has anyone find out why this is happening or how to fix this?
Thanks in advance

**Comment by brickfieldlabs** [comment]
Hi there,

Thanks for your query - please email support@brickfield.ie so we can reply.

We will close this ticket, as not about this block!

Regards

Gavin
